# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/task-manager-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.connection-timeout=10000
spring.jpa.generate-ddl=true    
spring.jpa.hibernate.ddl-auto=none

# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false

# Spring circular references
spring.main.allow-circular-references=true


spring.data.redis.host=localhost
spring.data.redis.port=6379


app.jwt.secret=secretkey
app.jwt.tokenExpiration=3m
app.jwt.refreshTokenExpiration= 30m 
