# Database
server:
  port: 8083

spring:
    r2dbc:
      url: r2dbc:pool:postgresql://localhost:5432/task-manager-db
      username: postgres
      password: postgres

#    datasource:
#        url: jdbc:postgresql://localhost:5432/task-manager-db
#        username: postgres
#        password: postgres
    hikari:
        connection-timeout: 10000

    jpa:
        generate-ddl: true
    hibernate:
        ddl-auto: none



    # Redis
    data:
        redis:
        host: localhost
        port: 6379

# Spring circular references
    main:
        allow-circular-references: true

# Server
server:
  port: 8080


app:
  auth: token
  jwt:
    password:
      encoder:
        secret: 0575102f800048672e80f530b6f6f1fe2108b007316302751632e14b0c4df7f6
        iteration: 64
        keyLenght: 256
    secret: 79d21d70352b250e4d8bd109a9a113e3ae80f444052048165553482e250827e5
    #seconds
    expiration: 3600
    issuer: esty