server:
  port: 8083

spring:
    data:
      redis:
        host: localhost
        port: 6379
    sql:

      init:
        mode: always
        schema-locations: classpath:init-sql.sql
        continue-on-error: true

    r2dbc:
      url: r2dbc:pool:postgresql://localhost:5432/task-manager-db
      username: postgres
      password: postgres

    hikari:
        connection-timeout: 10000
    jpa:
        generate-ddl: true
    hibernate:
        ddl-auto: none


    main:
        allow-circular-references: true


app:
  auth: token
  jwt:
    password:
      encoder:
        secret: 0575102f800048672e80f530b6f6f1fe2108b007316302751632e14b0c4df7f6
        iteration: 64
        keyLenght: 256
    secret: 79d21d70352b250e4d8bd109a9a113e3ae80f444052048165553482e250827e5
    #seconds
    expiration: 600000
    issuer: esty
    refreshExpiration: 604800000